# Generated by Django 5.0.4 on 2024-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='questionnaires/'),
        ),
    ]
